### ISSUE TITLE
Missing resources/wrong path?

### ISSUE THREAD

**Issue by yeti7** [spark/spark-setup-ios-example#1]
In Xcode I'm getting error:
error: %path%/Resources/Images.xcassets/AppIcon.appiconset: No such file or directory
where %path% is the path to the directory containing the file for spark-setup-ios-example

Additionally when I do "pods update" I get:

Update all pods
Analyzing dependencies
Fetching podspec for `SparkSetup` from `../spark-setup-ios`
[!] No podspec found for `SparkSetup` in `../spark-setup-ios`

Are there some additional steps required to make this example work?

**Comment by yeti7** [comment]
Later figured it out.
This example depends on code from https://github.com/spark/spark-sdk-ios being in sibling directory called "spark-sdk-ios"

**Comment by anthonywebb** [comment]
@yeti7 I think I am stuck one the same issue, what do you mean by "sibling directory", I currently have a folder with:

projectfolder
-- spark-sdk-ios	
-- spark-setup-ios

When I cd to spark-setup-ios and run "pod update", I get:
Update all pods
Analyzing dependencies
Fetching podspec for `SparkSetup` from `../spark-setup-ios`
[!] No podspec found for `SparkSetup` in `../spark-setup-ios`

**Comment by yeti7** [comment]
I tried the process again and it took me some time to reproduce the working setup.
Here are the steps:
- download: spark-sdk-ios
- download: spark-setup-ios
- download: spark-setup-ios-example

unzip them all to the same folder without -master in the name. You'll have folders
spark-sdk-ios
spark-setup-ios
spark-setup-ios-example

run
pod update inside of each folder in the order listed
see if build succeeds

**Comment by chap** [comment]
@yeti7 :+1:
